title: "Dongho Kim | Software Engineer"
description: "Projects, Code, and Career Journey"
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

locale: "ko-KR"

paginate: 5
paginate_path: /page:num/

author:
  name: "Dongho Kim"
  avatar: "/assets/images/avatar.png"
  bio: "Senior CS Student @ U of Regina | IT, Cybersecurity, Automation"
  location: "Canada / South Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dkssyd07"
