title: "Dongho Kim"
tagline: "Cybersecurity, Automation, and Smart Projects"
description: >-
  Portfolio and blog of Dongho Kim.
url: "https://dkssyd07.github.io/"
baseurl: ""  # 공백이면 루트에서 운영

theme: jekyll-theme-chirpy
lang: ko-KR

github:
  username: your-github-username

social:
  name: Dongho Kim
  email: your@email.com
  links:
    - https://github.com/dkssyd07
    - www.linkedin.com/in/dongho-kim-64a0481b8